development:
 cloud_name: hc2mzwyem
 api_key: '554459854886322'
 api_secret: lmSrInRo4OqJFtHwtIIT1FTlduE
 enhance_image_tag: true
 static_image_support: true

production:
 cloud_name: hc2mzwyem
 api_key: '554459854886322'
 api_secret: lmSrInRo4OqJFtHwtIIT1FTlduE
 enhance_image_tag: true
 static_image_support: true
